{
  "schema_version": "1.4.0",
  "id": "GHSA-m4jx-m5hg-qrxx",
  "modified": "2025-06-04T01:30:24Z",
  "published": "2025-05-31T03:30:33Z",
  "aliases": [
    "CVE-2018-25111"
  ],
  "summary": "django-helpdesk Allows Sensitive Data Exposure",
  "details": "django-helpdesk before 1.0.0 allows Sensitive Data Exposure because of os.umask(0) in models.py.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django-helpdesk"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.0.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-25111"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django-helpdesk/django-helpdesk/issues/591"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django-helpdesk/django-helpdesk/pull/1120"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django-helpdesk/django-helpdesk/commit/f872ec252769bee5a88b06d07d3634e580c67bcc"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/django-helpdesk/django-helpdesk"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django-helpdesk/django-helpdesk/releases/tag/v1.0.0"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django-helpdesk/PYSEC-2025-44.yaml"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-277"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2025-06-04T01:30:23Z",
    "nvd_published_at": "2025-05-31T01:15:19Z"
  }
}