{
  "schema_version": "1.4.0",
  "id": "GHSA-v7vw-mgw4-jqvj",
  "modified": "2025-07-10T09:32:30Z",
  "published": "2025-07-10T09:32:30Z",
  "aliases": [
    "CVE-2025-38321"
  ],
  "details": "In the Linux kernel, the following vulnerability has been resolved:\n\nsmb: Log an error when close_all_cached_dirs fails\n\nUnder low-memory conditions, close_all_cached_dirs() can't move the\ndentries to a separate list to dput() them once the locks are dropped.\nThis will result in a \"Dentry still in use\" error, so add an error\nmessage that makes it clear this is what happened:\n\n[  495.281119] CIFS: VFS: \\\\otters.example.com\\share Out of memory while dropping dentries\n[  495.281595] ------------[ cut here ]------------\n[  495.281887] BUG: Dentry ffff888115531138{i=78,n=/}  still in use (2) [unmount of cifs cifs]\n[  495.282391] WARNING: CPU: 1 PID: 2329 at fs/dcache.c:1536 umount_check+0xc8/0xf0\n\nAlso, bail out of looping through all tcons as soon as a single\nallocation fails, since we're already in trouble, and kmalloc() attempts\nfor subseqeuent tcons are likely to fail just like the first one did.",
  "severity": [],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-38321"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/43f26094d6702e494e800532c3f1606e7a68eb30"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/4479db143390bdcadc1561292aab579cdfa9f6c6"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/a2182743a8b4969481f64aec4908ff162e8a206c"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/b8ced2b9a23a1a2c1e0ed8d0d02512e51bdf38da"
    }
  ],
  "database_specific": {
    "cwe_ids": [],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-07-10T09:15:26Z"
  }
}