{
  "schema_version": "1.4.0",
  "id": "GHSA-pvcp-73cg-6f77",
  "modified": "2025-04-21T22:52:15Z",
  "published": "2022-05-17T03:05:11Z",
  "aliases": [
    "CVE-2016-4807"
  ],
  "summary": "Web2py Reflected XSS vulnerability",
  "details": "Web2py versions 2.14.5 and below was affected by Reflected XSS vulnerability, which allows an attacker to perform an XSS attack on logged in user (admin).",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "web2py"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "2.14.5"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-4807"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/web2py/web2py"
    },
    {
      "type": "WEB",
      "url": "https://www.exploit-db.com/exploits/39821"
    },
    {
      "type": "WEB",
      "url": "http://packetstormsecurity.com/files/137070/Web2py-2.14.5-CSRF-XSS-Local-File-Inclusion.html"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-79"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2025-04-21T22:52:15Z",
    "nvd_published_at": "2017-01-11T16:59:00Z"
  }
}